apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: rook-ceph
    meta.helm.sh/release-namespace: rook-ceph
  creationTimestamp: "2024-01-30T12:10:14Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: objectbuckets.objectbucket.io
  resourceVersion: "884062"
  uid: fcbade61-fcd8-48c2-8f33-8be3355351e0
spec:
  conversion:
    strategy: None
  group: objectbucket.io
  names:
    kind: ObjectBucket
    listKind: ObjectBucketList
    plural: objectbuckets
    shortNames:
    - ob
    - obs
    singular: objectbucket
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              additionalState:
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              authentication:
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                nullable: true
                type: object
              claimRef:
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              endpoint:
                nullable: true
                properties:
                  additionalConfig:
                    nullable: true
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  bucketHost:
                    type: string
                  bucketName:
                    type: string
                  bucketPort:
                    format: int32
                    type: integer
                  region:
                    type: string
                  subRegion:
                    type: string
                type: object
              reclaimPolicy:
                type: string
              storageClassName:
                type: string
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ObjectBucket
    listKind: ObjectBucketList
    plural: objectbuckets
    shortNames:
    - ob
    - obs
    singular: objectbucket
  conditions:
  - lastTransitionTime: "2024-01-30T12:10:14Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-01-30T12:10:14Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
