- name: Setup Docker and NetworkManager with Calico
  hosts: dev
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install essential packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - apt-transport-https
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Load bridge module
      ansible.builtin.modprobe:
        name: br_netfilter
      become: true

    - name: Set sysctl parameter
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        sysctl_set: yes
        state: present
        reload: true

    - name: Add Docker apt key
      apt_key:
        keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
        url: https://download.docker.com/linux/debian/gpg

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian buster stable
        state: present
        filename: docker.list
      become: true

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Install Docker Buildx plugin
      shell: >
        docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64

    - name: Install Docker Compose
      shell: >
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        && chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Create NetworkManager configuration for Calico
      blockinfile:
        path: /etc/NetworkManager/conf.d/calico.conf
        create: yes
        content: |
          [keyfile]
          unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:vxlan-v6.calico;interface-name:wireguard.cali;interface-name:wg-v6.cali

    - name: Set nf_conntrack_max using sysctl
      sysctl:
        name: net.netfilter.nf_conntrack_max
        value: 1000000
        state: present
      register: sysctl_result

    - name: Update sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.netfilter.nf_conntrack_max=1000000"
      when: sysctl_result.changed

    - name: Allow Tcp Forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "AllowTcpForwarding yes"
        state: present

    - name: Add user to docker group
      user:
        name: infracloud
        groups: docker
        append: yes


